version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/client"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "eslint-plugin-react-refresh"
        versions: [">= 0.5.0"]
  - package-ecosystem: "npm"
    directory: "/server"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
